---
--- Generated by PluginCreator
--- camera_movie gm
--- DateTime:2021-08-27
---

local path = Root.Instance():getGamePath():gsub("\\", "/") .. "lua/gm_client.lua"
local file, err = io.open(path, "r")
local GMItem
if file then
    GMItem = require("gm_client")
    file:close()
end
if not GMItem then
    GMItem = GM:createGMItem()
end

GMItem["飘字/UI白字"] = function(self)
    local textType = Define.FlyTextType.WhiteDamage
    Plugins.CallTargetPluginFunc("fly_text", "onShowUIFlyText", self, textType.color, "+300", textType.scale)
end

GMItem["飘字/miss"] = function(self)
    Plugins.CallTargetPluginFunc("fly_text", "onEntityShowFlyText", self, Define.FlyTextType.MissDamage, "miss")
end

GMItem["飘字/怪普通伤害"] = function(self)
    Plugins.CallTargetPluginFunc("fly_text", "onEntityShowFlyText", self, Define.FlyTextType.Damage, "20.6")
end

GMItem["飘字/暴击伤害"] = function(self)
    Plugins.CallTargetPluginFunc("fly_text", "onEntityShowFlyText", self, Define.FlyTextType.BlastDamage, "-80.6")
end

GMItem["飘字/其他玩家伤害"] = function(self)
    Plugins.CallTargetPluginFunc("fly_text", "onEntityShowFlyText", self, Define.FlyTextType.PlayerOtherDamage, "20.6")
end

GMItem["飘字/自己受到伤害"] = function(self)
    Plugins.CallTargetPluginFunc("fly_text", "onEntityShowFlyText", self, Define.FlyTextType.PlayerSelfDamage, "20.6")
end

GMItem["飘字/击落玩家"] = function(self)
    local textType = Define.FlyTextType.ShootDownFlyPlayer
    Plugins.CallTargetPluginFunc("fly_text", "onShowUIFlyText", self, textType.color, "10086", textType.scale)
end