---
--- Generated by PluginCreator
--- fly_new_tips gm
--- DateTime:2023-04-17
---

local path = Root.Instance():getGamePath():gsub("\\", "/") .. "lua/gm_client.lua"
local file, err = io.open(path, "r")
local GMItem
if file then
    GMItem = require("gm_client")
    file:close()
end
if not GMItem then
    GMItem = GM:createGMItem()
end

GMItem["fly_new_tips/c普通飘字"] = function()
    if not World.cfg.openGM then
        return
    end
    local color = string.format("[colour='%s']", "FF00FFFF")
    local content = "这是个飘字" .. color .. "提示" .. math.random(1, 10000000)
    Plugins.CallTargetPluginFunc("fly_new_tips", "pushFlyNewTipsText", content)
end

GMItem["fly_new_tips/c特殊飘字"] = function()
    if not World.cfg.openGM then
        return
    end
    local itemInfo = {
        type = Define.FlyNewTipsType.Special,
        content = {
            {
                sType = Define.FlySpecialTipsType.Text,
                text = "飘字1啊",
                fontSize = 20,                  -- 默认 World.cfg.fly_new_tipsSetting.fontSize
                textColours = "FFFF00FF",        -- 默认 World.cfg.fly_new_tipsSetting.textColours
                borderWidth = 3,        -- 默认 World.cfg.fly_new_tipsSetting.borderWidth
                borderColor = "FFFFFF00",        -- 默认 World.cfg.fly_new_tipsSetting.borderColor
            },
            {
                sType = Define.FlySpecialTipsType.Image,
                imgRes = "asset/imageset/icon_skill:skill_suolong_c_icon",
                width = 60,
                height = 60,
            },
            {
                sType = Define.FlySpecialTipsType.Text,
                text = "飘字2啊",
            },
            {
                sType = Define.FlySpecialTipsType.Image,
                imgRes = "asset/imageset/icon_skill:skill_suolong_c_icon"
            },
            {
                sType = Define.FlySpecialTipsType.Text,
                text = "飘字3啊",
                fontSize = 35,                  -- 默认 World.cfg.fly_new_tipsSetting.fontSize
                textColours = "FFFF0000",        -- 默认 World.cfg.fly_new_tipsSetting.textColours
                borderWidth = 2,        -- 默认 World.cfg.fly_new_tipsSetting.borderWidth
                borderColor = "FFFF0000",        -- 默认 World.cfg.fly_new_tipsSetting.borderColor
            },
            {
                sType = Define.FlySpecialTipsType.Image,
                imgRes = "asset/imageset/icon_skill:skill_suolong_c_icon",
                width = 30,
                height = 30,
            },
        }
    }
    Plugins.CallTargetPluginFunc("fly_new_tips", "pushFlyNewTipsSpecial", itemInfo)
end

GMItem["fly_new_tips/c普通广播"] = function()
    local content = "这是个飘字提示" .. os.time()
    Plugins.CallTargetPluginFunc("fly_new_tips", "boardCastOneFlyNewText", content)
end

GMItem["fly_new_tips/c特殊广播"] = function()
    local itemInfo = {
        type = Define.FlyNewTipsType.Special,
        content = {
            {
                sType = Define.FlySpecialTipsType.Text,
                text = "飘字1啊",
                fontSize = 20,                  -- 默认 World.cfg.fly_new_tipsSetting.fontSize
                textColours = "FFFF00FF",        -- 默认 World.cfg.fly_new_tipsSetting.textColours
                borderWidth = 3,        -- 默认 World.cfg.fly_new_tipsSetting.borderWidth
                borderColor = "FFFFFF00",        -- 默认 World.cfg.fly_new_tipsSetting.borderColor
            },
            {
                sType = Define.FlySpecialTipsType.Image,
                imgRes = "asset/imageset/icon_skill:skill_suolong_c_icon",
                width = 60,
                height = 60,
            },
            {
                sType = Define.FlySpecialTipsType.Text,
                text = "飘字2啊",
            },
            {
                sType = Define.FlySpecialTipsType.Image,
                imgRes = "asset/imageset/icon_skill:skill_suolong_c_icon"
            },
            {
                sType = Define.FlySpecialTipsType.Text,
                text = "飘字3啊",
                fontSize = 35,                  -- 默认 World.cfg.fly_new_tipsSetting.fontSize
                textColours = "FFFF0000",        -- 默认 World.cfg.fly_new_tipsSetting.textColours
                borderWidth = 2,        -- 默认 World.cfg.fly_new_tipsSetting.borderWidth
                borderColor = "FFFF0000",        -- 默认 World.cfg.fly_new_tipsSetting.borderColor
            },
            {
                sType = Define.FlySpecialTipsType.Image,
                imgRes = "asset/imageset/icon_skill:skill_suolong_c_icon",
                width = 30,
                height = 30,
            },
        }
    }
    Plugins.CallTargetPluginFunc("fly_new_tips", "boardCastFlyNewTipsSpecial", itemInfo)
end
