---
--- Generated by PluginCreator
--- game_role_common gm
--- DateTime:2023-03-03
---

local path = Root.Instance():getGamePath():gsub("\\", "/") .. "lua/gm_client.lua"
local file, err = io.open(path, "r")
local GMItem
if file then
    GMItem = require("gm_client")
    file:close()
end
if not GMItem then
    GMItem = GM:createGMItem()
end

---@type GameRoleCommonGMHelperClient
local GameRoleCommonGMHelperClient = T(Lib, "GameRoleCommonGMHelperClient")

--GMItem["角色通用/添加勾玉"] = GM:inputNumber(function(self, value)
--    GameRoleCommonGMHelperClient:addItem(self, Define.ITEM_ALIAS.AWAKE_CONSUME, value or 100)
--end)
--
--GMItem["角色通用/清除当前觉醒"] = function(self)
--    GameRoleCommonGMHelperClient:setAbilityAwake(self, 0)
--end
--
--GMItem["角色通用/设置觉醒等级"] = GM:inputNumber(function(self, value)
--    GameRoleCommonGMHelperClient:setAbilityAwake(self, value or 0)
--end)


--GMItem["game_role_common/一个彩蛋"] = function()
--end

 --GMItem["g2069/震屏测试"] = function()
 --    ---@type GameCameraControl
 --    local GameCameraControl = T(Lib, "GameCameraControl")
 --    GameCameraControl:shakeCamera(0.6,0.2,3,0.8)
 --end

GMItem["角色通用/打印危险指数"] = function(self)
    if not World.cfg.openGM then
        return
    end
    local dangerValue = Me:getDangerValue()
    local content = "危险指数：" .. dangerValue
    Plugins.CallTargetPluginFunc("fly_new_tips", "pushFlyNewTipsText", content)
end

GMItem["角色通用/引导特效"] = function(self)
    if not World.cfg.openGM then
        return
    end
    Me:showTaskGuideArrow(true)
end
GMItem["角色通用/关引导特效"] = function(self)
    if not World.cfg.openGM then
        return
    end
    Me:showTaskGuideArrow(false)
end

-- GMItem["角色通用/四选一礼包"] = function(self)
--     UI:openWindow("UI/game_role_common/gui/win_subscribe_ability_wnd")
-- end